// SPDX-FileCopyrightText: 2026 Robert Pelfrey <Robert@Pelfrey.de>
// SPDX-License-Identifier: GPL-3.0-or-later

//! Hardened C-build profile generation and generated-tree hygiene.

use super::artifact::{write_secure_artifact, write_secure_json_artifact};
use super::common::{ensure_real_directory_tree, executable_path};
use super::deps::C_SERVICES_CHAIN;
use crate::process::CommandRunner;
use crate::result::Finding;
use serde_json::{Map, Value, json};
use std::collections::BTreeMap;
use std::env;
use std::ffi::OsString;
use std::fs;
use std::path::Component;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};

pub(crate) const PROFILE: &str = "hardened";
pub(crate) const CMAKE_INJECTION: &str = "build/hardened/yafvs-hardening.cmake";
pub(crate) const CONFIGURATION: &str = "build/hardened/hardening-configuration.json";
pub(crate) const BUILD_MANIFEST: &str = "build/hardened/hardening-manifest.json";

const REQUIRED_FEATURES: [&str; 8] = [
    "format_security",
    "fortify",
    "stack_protector",
    "stack_clash",
    "relro",
    "now",
    "noexecstack",
    "pie",
];
const CONTROL_FLOW_ARCHITECTURES: [&str; 4] = ["x86_64", "amd64", "aarch64", "arm64"];
const PROBE_SOURCE: &[u8] = b"int main(void) { return 0; }\n";
static NEXT_PROBE: AtomicU64 = AtomicU64::new(0);

pub(crate) struct ProfileConfiguration {
    pub(crate) cmake_args: Vec<String>,
    pub(crate) failed_required: Vec<String>,
}

struct HardeningPlan {
    compiler_flags: Vec<String>,
    linker_flags: Vec<String>,
    evidence: BTreeMap<String, Value>,
    cmake_args: Vec<String>,
}

pub(crate) fn hardened_environment(repo_root: &Path) -> BTreeMap<OsString, OsString> {
    let mut environment = env::vars_os().collect::<BTreeMap<_, _>>();
    let prefix = repo_root.join("build/hardened/prefix");
    prepend_path_value(
        &mut environment,
        "PKG_CONFIG_PATH",
        &[
            prefix.join("lib/pkgconfig").display().to_string(),
            prefix.join("lib64/pkgconfig").display().to_string(),
        ],
    );
    environment.insert(
        OsString::from("CMAKE_PREFIX_PATH"),
        OsString::from(prefix.display().to_string()),
    );
    prepend_path_value(
        &mut environment,
        "LD_LIBRARY_PATH",
        &[
            prefix.join("lib").display().to_string(),
            prefix.join("lib64").display().to_string(),
        ],
    );
    environment
}

pub(crate) fn cmake_fresh_support(
    repo_root: &Path,
    runner: &dyn CommandRunner,
) -> Result<(), String> {
    let cmake = executable_path("cmake").ok_or_else(|| {
        "cmake is unavailable; hardened profiles require cmake with --fresh support".to_string()
    })?;
    let program = cmake.display().to_string();
    let output = runner
        .run_with(&program, &["--help"], Some(repo_root), None, None)
        .ok_or_else(|| {
            "installed cmake could not be inspected; cmake >= 3.24 is required for hardened profiles"
                .to_string()
        })?;
    if output.success && output.stdout.contains("--fresh") {
        Ok(())
    } else {
        Err(
            "installed cmake does not advertise --fresh; cmake >= 3.24 is required for hardened profiles"
                .into(),
        )
    }
}

pub(crate) fn profile_configuration(
    repo_root: &Path,
    runner: &dyn CommandRunner,
) -> Result<ProfileConfiguration, String> {
    let machine = env::consts::ARCH.to_string();
    let mut probe = |flags: &[String], link: bool| {
        hardened_flag_probe(repo_root, runner, flags, link).unwrap_or(false)
    };
    let mut plan = hardening_plan(&machine, &mut probe);
    let injection_path = repo_root.join(CMAKE_INJECTION);
    if let Some(argument) = plan
        .cmake_args
        .iter_mut()
        .find(|argument| argument.starts_with("-DCMAKE_PROJECT_INCLUDE="))
    {
        *argument = format!("-DCMAKE_PROJECT_INCLUDE={}", injection_path.display());
    }
    let mut injection = String::from(
        "# Generated by tools/yafvsctl; do not edit.\n\
         if(NOT YAFVS_HARDENING_OPTIONS_APPLIED)\n\
           set(YAFVS_HARDENING_OPTIONS_APPLIED TRUE)\n\
           add_compile_options(\n",
    );
    for flag in &plan.compiler_flags {
        injection.push_str("    ");
        injection.push_str(flag);
        injection.push('\n');
    }
    injection.push_str("  )\nendif()\n");
    write_secure_artifact(&injection_path, injection.as_bytes())
        .map_err(|error| format!("hardened CMake injection could not be written: {error}"))?;

    let configuration = json!({
        "schema_version": 1,
        "architecture": machine,
        "compile_options": plan.compiler_flags,
        "linker_options": plan.linker_flags,
        "features": plan.evidence,
        "cmake_injection": CMAKE_INJECTION,
    });
    write_secure_json_artifact(&repo_root.join(CONFIGURATION), &configuration)
        .map_err(|error| format!("hardened configuration could not be written: {error}"))?;

    let failed_required = required_features(&machine)
        .into_iter()
        .filter(|name| {
            configuration["features"][name]["status"]
                .as_str()
                .is_none_or(|status| status != "present")
        })
        .map(str::to_string)
        .collect();
    Ok(ProfileConfiguration {
        cmake_args: plan.cmake_args,
        failed_required,
    })
}

pub(crate) fn preflight_cleanup(repo_root: &Path) -> Finding {
    let build_root = repo_root.join("build/hardened");
    let paths = C_SERVICES_CHAIN
        .iter()
        .map(|component| build_root.join(component))
        .chain(std::iter::once(build_root.join("prefix")))
        .collect::<Vec<_>>();
    let requested_paths = paths
        .iter()
        .map(|path| relative_path(repo_root, path))
        .collect::<Vec<_>>();
    if let Err(error) = validate_profile_parent(repo_root) {
        return Finding::new(
            "fail",
            "build-c-services.hardened-preflight",
            "Hardened generated-tree cleanup refused an unsafe build parent.".into(),
        )
        .with_path("build/hardened")
        .with_details(json!({
            "requested_paths": requested_paths,
            "removed_paths": [],
            "errors": [{"path": "build/hardened", "error": error}],
        }));
    }

    let mut removed = Vec::new();
    let mut errors = Vec::new();
    for path in paths {
        let relative = relative_path(repo_root, &path);
        match fs::symlink_metadata(&path) {
            Ok(metadata) if metadata.file_type().is_symlink() || metadata.file_type().is_file() => {
                match fs::remove_file(&path) {
                    Ok(()) => removed.push(relative),
                    Err(error) => {
                        errors.push(json!({"path": relative, "error": error.to_string()}))
                    }
                }
            }
            Ok(metadata) if metadata.file_type().is_dir() => match fs::remove_dir_all(&path) {
                Ok(()) => removed.push(relative),
                Err(error) => errors.push(json!({"path": relative, "error": error.to_string()})),
            },
            Ok(_) => errors.push(json!({"path": relative, "error": "special file"})),
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => errors.push(json!({"path": relative, "error": error.to_string()})),
        }
    }
    Finding::new(
        if errors.is_empty() { "pass" } else { "fail" },
        "build-c-services.hardened-preflight",
        if errors.is_empty() {
            "Hardened generated component trees and dependency prefix were reset before the build chain."
        } else {
            "Hardened generated component trees and dependency prefix could not be fully reset."
        }
        .into(),
    )
    .with_path("build/hardened")
    .with_details(json!({
        "requested_paths": requested_paths,
        "removed_paths": removed,
        "errors": errors,
    }))
}

pub(crate) fn invalidate_manifest(repo_root: &Path) -> Result<(), String> {
    validate_profile_parent(repo_root)?;
    let path = repo_root.join(BUILD_MANIFEST);
    match fs::symlink_metadata(&path) {
        Ok(_) => fs::remove_file(&path)
            .map_err(|error| format!("prior hardened manifest could not be removed: {error}")),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(format!(
            "prior hardened manifest could not be inspected: {error}"
        )),
    }
}

fn hardening_plan(machine: &str, probe: &mut impl FnMut(&[String], bool) -> bool) -> HardeningPlan {
    let mut compiler_flags = strings(&[
        "-O2",
        "-g",
        "-DNDEBUG",
        "-Wall",
        "-Wextra",
        "-Wformat",
        "-Wformat=2",
    ]);
    let mut linker_flags = Vec::new();
    let mut evidence = BTreeMap::new();

    compiler_feature(
        "format_security",
        strings(&["-Werror=format-security"]),
        &mut compiler_flags,
        &mut evidence,
        probe,
    );
    compiler_feature(
        "format_nonliteral_compat",
        strings(&["-Wno-error=format-nonliteral"]),
        &mut compiler_flags,
        &mut evidence,
        probe,
    );
    let level_three_flags = strings(&["-O2", "-U_FORTIFY_SOURCE", "-D_FORTIFY_SOURCE=3"]);
    let level_three_supported = probe(&level_three_flags, false);
    let level = if level_three_supported { 3 } else { 2 };
    compiler_feature(
        "fortify",
        vec![
            "-U_FORTIFY_SOURCE".into(),
            format!("-D_FORTIFY_SOURCE={level}"),
        ],
        &mut compiler_flags,
        &mut evidence,
        probe,
    );
    if let Some(item) = evidence.get_mut("fortify").and_then(Value::as_object_mut) {
        item.insert(
            "level_three_supported".into(),
            Value::Bool(level_three_supported),
        );
        item.insert("selected_level".into(), Value::from(level));
    }
    compiler_feature(
        "stack_protector",
        strings(&["-fstack-protector-strong"]),
        &mut compiler_flags,
        &mut evidence,
        probe,
    );
    compiler_feature(
        "stack_clash",
        strings(&["-fstack-clash-protection"]),
        &mut compiler_flags,
        &mut evidence,
        probe,
    );

    let normalized_machine = machine.to_ascii_lowercase();
    match normalized_machine.as_str() {
        "x86_64" | "amd64" => compiler_feature(
            "control_flow_protection",
            strings(&["-fcf-protection=full"]),
            &mut compiler_flags,
            &mut evidence,
            probe,
        ),
        "aarch64" | "arm64" => compiler_feature(
            "control_flow_protection",
            strings(&["-mbranch-protection=standard"]),
            &mut compiler_flags,
            &mut evidence,
            probe,
        ),
        _ => {
            evidence.insert(
                "control_flow_protection".into(),
                json!({
                    "status": "unsupported",
                    "flags": [],
                    "reason": format!("no profile flag for {normalized_machine}"),
                }),
            );
        }
    }

    for (name, flags) in [
        ("relro", strings(&["-Wl,-z,relro"])),
        ("now", strings(&["-Wl,-z,now"])),
        ("noexecstack", strings(&["-Wl,-z,noexecstack"])),
    ] {
        linker_feature(name, flags, &mut linker_flags, &mut evidence, probe);
    }
    let pie_probe = strings(&["-fPIE", "-pie"]);
    let pie_supported = probe(&pie_probe, true);
    evidence.insert(
        "pie".into(),
        json!({
            "status": if pie_supported { "present" } else { "unsupported" },
            "flags": ["CMAKE_POSITION_INDEPENDENT_CODE=ON", "-pie"],
        }),
    );

    let injection = format!(
        "-DCMAKE_PROJECT_INCLUDE={}",
        Path::new(CMAKE_INJECTION).display()
    );
    let executable_linker_flags = if pie_supported {
        linker_flags
            .iter()
            .cloned()
            .chain(std::iter::once("-pie".into()))
            .collect::<Vec<_>>()
    } else {
        linker_flags.clone()
    };
    let cmake_args = vec![
        "-DCMAKE_BUILD_TYPE=Release".into(),
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON".into(),
        "-DCMAKE_POSITION_INDEPENDENT_CODE=ON".into(),
        injection,
        format!("-DCMAKE_SHARED_LINKER_FLAGS={}", linker_flags.join(" ")),
        format!("-DCMAKE_MODULE_LINKER_FLAGS={}", linker_flags.join(" ")),
        format!(
            "-DCMAKE_EXE_LINKER_FLAGS={}",
            executable_linker_flags.join(" ")
        ),
    ];
    HardeningPlan {
        compiler_flags,
        linker_flags,
        evidence,
        cmake_args,
    }
}

fn compiler_feature(
    name: &str,
    flags: Vec<String>,
    compiler_flags: &mut Vec<String>,
    evidence: &mut BTreeMap<String, Value>,
    probe: &mut impl FnMut(&[String], bool) -> bool,
) {
    let supported = probe(&flags, false);
    evidence.insert(name.into(), feature_evidence(supported, &flags));
    if supported {
        compiler_flags.extend(flags);
    }
}

fn linker_feature(
    name: &str,
    flags: Vec<String>,
    linker_flags: &mut Vec<String>,
    evidence: &mut BTreeMap<String, Value>,
    probe: &mut impl FnMut(&[String], bool) -> bool,
) {
    let supported = probe(&flags, true);
    evidence.insert(name.into(), feature_evidence(supported, &flags));
    if supported {
        linker_flags.extend(flags);
    }
}

fn feature_evidence(supported: bool, flags: &[String]) -> Value {
    let mut item = Map::new();
    item.insert(
        "status".into(),
        Value::String(if supported { "present" } else { "unsupported" }.into()),
    );
    item.insert(
        "flags".into(),
        Value::Array(flags.iter().cloned().map(Value::String).collect()),
    );
    Value::Object(item)
}

fn hardened_flag_probe(
    repo_root: &Path,
    runner: &dyn CommandRunner,
    flags: &[String],
    link: bool,
) -> Result<bool, String> {
    let compiler = env::var("CC").unwrap_or_else(|_| "cc".into());
    let compiler = shlex::split(&compiler)
        .filter(|items| !items.is_empty())
        .ok_or_else(|| "CC does not contain a valid compiler command".to_string())?;
    if executable_path(&compiler[0]).is_none() {
        return Ok(false);
    }
    let temporary = ProbeDirectory::create(repo_root)?;
    let output = temporary.path.join("probe");
    let mut arguments = compiler[1..].to_vec();
    arguments.push("-Werror".into());
    arguments.extend_from_slice(flags);
    arguments.extend(strings(&["-x", "c", "-"]));
    if link {
        arguments.extend(vec!["-o".into(), output.display().to_string()]);
    } else {
        arguments.extend(vec!["-c".into(), "-o".into(), output.display().to_string()]);
    }
    let refs = arguments.iter().map(String::as_str).collect::<Vec<_>>();
    Ok(runner
        .run_with_input(
            &compiler[0],
            &refs,
            Some(repo_root),
            Some(&hardened_environment(repo_root)),
            None,
            Some(PROBE_SOURCE),
        )
        .is_some_and(|result| result.success))
}

struct ProbeDirectory {
    path: PathBuf,
}

impl ProbeDirectory {
    fn create(repo_root: &Path) -> Result<Self, String> {
        let root =
            ensure_real_directory_tree(repo_root, Path::new("build/hardened/.feature-probes"))
                .map_err(|error| format!("feature-probe directory is unsafe: {error}"))?;
        for _ in 0..64 {
            let number = NEXT_PROBE.fetch_add(1, Ordering::Relaxed);
            let path = root.join(format!("probe-{}-{number}", std::process::id()));
            match fs::create_dir(&path) {
                Ok(()) => return Ok(Self { path }),
                Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => {}
                Err(error) => {
                    return Err(format!(
                        "feature-probe temporary directory could not be created: {error}"
                    ));
                }
            }
        }
        Err("feature-probe temporary directory namespace is exhausted".into())
    }
}

impl Drop for ProbeDirectory {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.path);
    }
}

fn required_features(machine: &str) -> Vec<&'static str> {
    let mut required = REQUIRED_FEATURES.to_vec();
    if CONTROL_FLOW_ARCHITECTURES.contains(&machine.to_ascii_lowercase().as_str()) {
        required.push("control_flow_protection");
    }
    required
}

pub(crate) fn validate_profile_parent(repo_root: &Path) -> Result<(), String> {
    for path in [repo_root.join("build"), repo_root.join("build/hardened")] {
        match fs::symlink_metadata(&path) {
            Ok(metadata) if metadata.file_type().is_symlink() => {
                return Err(format!(
                    "{} is a symlinked build parent",
                    relative_path(repo_root, &path)
                ));
            }
            Ok(metadata) if !metadata.file_type().is_dir() => {
                return Err(format!(
                    "{} is not a directory",
                    relative_path(repo_root, &path)
                ));
            }
            Ok(_) => {}
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
            Err(error) => {
                return Err(format!(
                    "{} could not be inspected: {error}",
                    relative_path(repo_root, &path)
                ));
            }
        }
    }
    Ok(())
}

pub(crate) fn validate_existing_profile_directory(
    repo_root: &Path,
    path: &Path,
) -> Result<(), String> {
    let relative = path
        .strip_prefix(repo_root)
        .map_err(|_| "hardened directory escaped the repository".to_string())?;
    let root_metadata = fs::symlink_metadata(repo_root)
        .map_err(|error| format!("repository root could not be inspected: {error}"))?;
    if !root_metadata.file_type().is_dir() || root_metadata.file_type().is_symlink() {
        return Err("repository root is not a real directory".into());
    }
    let mut current = repo_root.to_path_buf();
    for component in relative.components() {
        let Component::Normal(component) = component else {
            return Err("hardened directory contains an unsafe path component".into());
        };
        current.push(component);
        match fs::symlink_metadata(&current) {
            Ok(metadata) if metadata.file_type().is_dir() && !metadata.file_type().is_symlink() => {
            }
            Ok(_) => {
                return Err(format!(
                    "{} is not a real directory",
                    relative_path(repo_root, &current)
                ));
            }
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => return Ok(()),
            Err(error) => {
                return Err(format!(
                    "{} could not be inspected: {error}",
                    relative_path(repo_root, &current)
                ));
            }
        }
    }
    Ok(())
}

fn prepend_path_value(
    environment: &mut BTreeMap<OsString, OsString>,
    name: &str,
    values: &[String],
) {
    let key = OsString::from(name);
    let mut values = values.to_vec();
    if let Some(current) = environment.get(&key).and_then(|value| value.to_str())
        && !current.is_empty()
    {
        values.push(current.to_string());
    }
    environment.insert(key, OsString::from(values.join(":")));
}

fn strings(values: &[&str]) -> Vec<String> {
    values.iter().map(|value| (*value).to_string()).collect()
}

fn relative_path(repo_root: &Path, path: &Path) -> String {
    path.strip_prefix(repo_root)
        .unwrap_or(path)
        .display()
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::process::ProcessOutput;
    use std::os::unix::fs::PermissionsExt;
    use std::os::unix::fs::symlink;

    struct SuccessRunner;

    impl CommandRunner for SuccessRunner {
        fn run(&self, _program: &str, _args: &[&str]) -> Option<ProcessOutput> {
            Some(ProcessOutput {
                success: true,
                exit_code: Some(0),
                stdout: String::new(),
                stderr: String::new(),
            })
        }
    }

    fn fixture(name: &str) -> PathBuf {
        let root = env::temp_dir().join(format!(
            "yafvsctl-build-hardening-{name}-{}-{}",
            std::process::id(),
            NEXT_PROBE.fetch_add(1, Ordering::Relaxed)
        ));
        fs::create_dir_all(&root).unwrap();
        root
    }

    #[test]
    fn profile_configuration_writes_private_artifacts_and_absolute_injection_argument() {
        let root = fixture("configuration");
        let configuration = profile_configuration(&root, &SuccessRunner).unwrap();
        assert!(configuration.failed_required.is_empty());
        assert!(configuration.cmake_args.iter().any(|argument| {
            argument
                == &format!(
                    "-DCMAKE_PROJECT_INCLUDE={}",
                    root.join(CMAKE_INJECTION).display()
                )
        }));
        let payload: Value =
            serde_json::from_slice(&fs::read(root.join(CONFIGURATION)).unwrap()).unwrap();
        assert_eq!(payload["schema_version"], 1);
        assert_eq!(payload["cmake_injection"], CMAKE_INJECTION);
        assert_eq!(
            fs::metadata(root.join(CMAKE_INJECTION))
                .unwrap()
                .permissions()
                .mode()
                & 0o777,
            0o600
        );
        assert_eq!(
            fs::metadata(root.join(CONFIGURATION))
                .unwrap()
                .permissions()
                .mode()
                & 0o777,
            0o600
        );
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn level_two_fortify_fallback_and_cmake_order_match_the_contract() {
        let mut probe =
            |flags: &[String], _link: bool| !flags.iter().any(|flag| flag == "-D_FORTIFY_SOURCE=3");
        let plan = hardening_plan("x86_64", &mut probe);
        assert_eq!(plan.evidence["fortify"]["selected_level"], 2);
        assert_eq!(
            plan.evidence["fortify"]["level_three_supported"],
            Value::Bool(false)
        );
        assert!(
            plan.compiler_flags
                .contains(&"-D_FORTIFY_SOURCE=2".to_string())
        );
        assert_eq!(
            &plan.cmake_args[..3],
            [
                "-DCMAKE_BUILD_TYPE=Release",
                "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
                "-DCMAKE_POSITION_INDEPENDENT_CODE=ON",
            ]
        );
        assert!(
            plan.cmake_args
                .last()
                .unwrap()
                .ends_with("-Wl,-z,noexecstack -pie")
        );
    }

    #[test]
    fn unsupported_architecture_does_not_require_control_flow_protection() {
        assert!(!required_features("riscv64").contains(&"control_flow_protection"));
        let mut probe = |_flags: &[String], _link: bool| true;
        let plan = hardening_plan("riscv64", &mut probe);
        assert_eq!(
            plan.evidence["control_flow_protection"]["status"],
            "unsupported"
        );
    }

    #[test]
    fn preflight_removes_only_registered_generated_trees() {
        let root = fixture("cleanup");
        for component in C_SERVICES_CHAIN {
            fs::create_dir_all(root.join("build/hardened").join(component)).unwrap();
        }
        fs::create_dir_all(root.join("build/hardened/prefix")).unwrap();
        fs::create_dir_all(root.join("build/hardened/unrelated")).unwrap();
        let finding = preflight_cleanup(&root);
        assert_eq!(finding.status, "pass");
        assert!(root.join("build/hardened/unrelated").is_dir());
        assert!(
            C_SERVICES_CHAIN
                .iter()
                .all(|component| !root.join("build/hardened").join(component).exists())
        );
        fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn preflight_refuses_a_symlinked_build_parent() {
        let root = fixture("symlink");
        let outside = fixture("outside");
        fs::write(outside.join("sentinel"), "keep").unwrap();
        symlink(&outside, root.join("build")).unwrap();
        let finding = preflight_cleanup(&root);
        assert_eq!(finding.status, "fail");
        assert_eq!(finding.check, "build-c-services.hardened-preflight");
        assert_eq!(
            fs::read_to_string(outside.join("sentinel")).unwrap(),
            "keep"
        );
        fs::remove_file(root.join("build")).unwrap();
        fs::remove_dir_all(root).unwrap();
        fs::remove_dir_all(outside).unwrap();
    }
}
