# SPDX-FileCopyrightText: 2026 Robert Pelfrey <Robert@Pelfrey.de>
# SPDX-License-Identifier: GPL-3.0-or-later

listener 1883 0.0.0.0
allow_anonymous false
password_file /mosquitto/config-secrets/passwords
acl_file /mosquitto/config-secrets/mosquitto.acl
max_connections 16
max_inflight_messages 20
max_queued_messages 1000
max_packet_size 4194304
persistence true
persistence_location /mosquitto/data/
log_dest stdout
