# SPDX-FileCopyrightText: 2025 Greenbone AG
# TurboVAS modifications Copyright (C) 2026 Robert Pelfrey <Robert@Pelfrey.de>.
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
"""
GMP Request implementations for GMP version 22.6.
"""

from .._entity_id import EntityID
from .._version import Version
from ..v225 import (
    Aggregates,
    AggregateStatistic,
    AlertCondition,
    AlertEvent,
    AlertMethod,
    Alerts,
    AliveTest,
    Authentication,
    CertBundAdvisories,
    Cpes,
    CredentialFormat,
    Credentials,
    CredentialType,
    Cves,
    DfnCertAdvisories,
    EntityType,
    Feed,
    FeedType,
    Help,
    HelpFormat,
    Hosts,
    HostsOrdering,
    InfoType,
    Nvts,
    OperatingSystems,
    Overrides,
    PortLists,
    PortRangeType,
    ReportFormats,
    ReportFormatType,
    Results,
    ScanConfigs,
    Scanners,
    ScannerType,
    Schedules,
    SecInfo,
    Severity,
    SnmpAuthAlgorithm,
    SnmpPrivacyAlgorithm,
    SortOrder,
    SystemReports,
    Tags,
    Targets,
    Tasks,
    TLSCertificates,
    TrashCan,
    UserAuthType,
    Users,
    UserSettings,
    Vulnerabilities,
)
from ._filters import Filters, FilterType
from ._report_configs import ReportConfigParameter, ReportConfigs
from ._reports import Reports
from ._resource_names import ResourceNames, ResourceType
from ._scopes import Scopes

__all__ = (
    "AggregateStatistic",
    "Aggregates",
    "AlertCondition",
    "AlertEvent",
    "AlertMethod",
    "Alerts",
    "AliveTest",
    "Authentication",
    "CertBundAdvisories",
    "Cpes",
    "CredentialFormat",
    "CredentialType",
    "Credentials",
    "Cves",
    "DfnCertAdvisories",
    "EntityID",
    "EntityType",
    "Feed",
    "FeedType",
    "FilterType",
    "Filters",
    "Help",
    "HelpFormat",
    "Hosts",
    "HostsOrdering",
    "InfoType",
    "Nvts",
    "OperatingSystems",
    "Overrides",
    "PortLists",
    "PortRangeType",
    "ReportConfigParameter",
    "ReportConfigs",
    "ReportFormatType",
    "ReportFormats",
    "Reports",
    "ResourceNames",
    "ResourceType",
    "Results",
    "ScanConfigs",
    "Scopes",
    "ScannerType",
    "Scanners",
    "Schedules",
    "SecInfo",
    "Severity",
    "SnmpAuthAlgorithm",
    "SnmpPrivacyAlgorithm",
    "SortOrder",
    "SystemReports",
    "TLSCertificates",
    "Tags",
    "Targets",
    "Tasks",
    "TrashCan",
    "UserAuthType",
    "UserSettings",
    "Users",
    "Version",
    "Vulnerabilities",
)
