# SPDX-FileCopyrightText: 2025 Greenbone AG
# TurboVAS modifications Copyright (C) 2026 Robert Pelfrey <Robert@Pelfrey.de>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
GMP Request implementations for GMP version 22.7.
"""

from gvm.protocols.gmp.requests.v227._scanners import Scanners, ScannerType

from .._entity_id import EntityID
from .._version import Version
from ..v226 import (
    Aggregates,
    AggregateStatistic,
    AliveTest,
    CertBundAdvisories,
    Cpes,
    CredentialFormat,
    Credentials,
    CredentialType,
    Cves,
    DfnCertAdvisories,
    EntityType,
    Feed,
    FeedType,
    Filters,
    FilterType,
    Help,
    HelpFormat,
    Hosts,
    HostsOrdering,
    InfoType,
    Nvts,
    OperatingSystems,
    Overrides,
    PortLists,
    PortRangeType,
    ReportFormats,
    ReportFormatType,
    Reports,
    ResourceNames,
    ResourceType,
    ScanConfigs,
    Schedules,
    SecInfo,
    Severity,
    SnmpAuthAlgorithm,
    SnmpPrivacyAlgorithm,
    SortOrder,
    SystemReports,
    Targets,
    Tasks,
    TLSCertificates,
    TrashCan,
    UserAuthType,
    Users,
    UserSettings,
    Vulnerabilities,
)

__all__ = (
    "AggregateStatistic",
    "Aggregates",
    "AliveTest",
    "CertBundAdvisories",
    "Cpes",
    "CredentialFormat",
    "CredentialType",
    "Credentials",
    "Cves",
    "DfnCertAdvisories",
    "EntityID",
    "EntityType",
    "Feed",
    "FeedType",
    "FilterType",
    "Filters",
    "Help",
    "HelpFormat",
    "Hosts",
    "HostsOrdering",
    "InfoType",
    "Nvts",
    "OperatingSystems",
    "Overrides",
    "PortLists",
    "PortRangeType",
    "ReportFormatType",
    "ReportFormats",
    "Reports",
    "ResourceNames",
    "ResourceType",
    "ScanConfigs",
    "ScannerType",
    "Scanners",
    "Schedules",
    "SecInfo",
    "Severity",
    "SnmpAuthAlgorithm",
    "SnmpPrivacyAlgorithm",
    "SortOrder",
    "SystemReports",
    "TLSCertificates",
    "Targets",
    "Tasks",
    "TrashCan",
    "UserAuthType",
    "UserSettings",
    "Users",
    "Version",
    "Vulnerabilities",
)
